### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by tac0x2a** [tac0x2a/lake_weed#9]
```
[ERROR] 2020-07-21 01:08:02,066 | ./grebe.py(L113) | '<' not supported between instances of 'str' and 'NoneType',
    from_to = "".join(sorted([from_, to])),
  File "/usr/local/lib/python3.8/site-packages/lakeweed/clickhouse.py", line 220, in __type_map,
    (correct_type, converter) = __type_map(current_type, new_col),
  File "/usr/local/lib/python3.8/site-packages/lakeweed/clickhouse.py", line 56, in data_string2type_value,
    (columns, types, values_list) = d2c.data_string2type_value(payload, specified_types=spec_types),
  File "./grebe.py", line 104, in callback,
Traceback (most recent call last):,
TypeError: '<' not supported between instances of 'str' and 'NoneType'
```

**Comment by tac0x2a** [comment]
Fix in #10
